######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 26 07:03:44 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sortdialog.h
FORMS += sortdialog.ui
SOURCES += main.cpp sortdialog.cpp
